# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6.QtCore import Qt, QCoreApplication, QMetaObject, QRect
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QComboBox, QDialog, QHBoxLayout, QLabel, QPushButton, QVBoxLayout, QTableWidget




class ScanDialog(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Basic QDialog")
        self.setGeometry(100, 100, 300, 100)
        self.button = QPushButton("Load Data")
        self.button.clicked.connect(self.load_data)
        print("connected button")
        #Create table
        self.table = QTableWidget()
        print("Created table")
        self.table.setColumnCount(9)
        self.table.setHorizontalHeaderLabels(["RIP", "Min size", "Max size", "Min addr", "Max addr", "Possible range", "Symbolic data?", "Symbolic addr?", "Symbolic size?"])
        self.table.setRowCount(0)
        print("Initialized table")
        # Layout setup
        
        left_layout = QVBoxLayout()
        left_layout.addWidget(self.button)
        left_layout.addStretch()
        print("Initialized left layout")
        main_layout = QHBoxLayout()
        main_layout.addLayout(left_layout)
        main_layout.addWidget(self.table)
        print("Initialized main layout")
        self.setLayout(main_layout)


    def load_data(self):
        #self.button.setText("Clicked!")
        pass
